# Generated by Django 4.1.7 on 2023-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="weather_city",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="weather_country",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="weather_latitude",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="weather_longitude",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
