# Generated by Django 4.1.7 on 2023-11-25 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_alter_weather_weather_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weather_api", models.CharField(max_length=200)),
                ("news_api", models.CharField(max_length=200)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-updated", "-created"],
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.RemoveField(
            model_name="news",
            name="news_api",
        ),
        migrations.RemoveField(
            model_name="weather",
            name="weather_api",
        ),
    ]
