# Generated by Django 4.1.7 on 2023-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0003_userdata_delete_user_remove_news_news_api_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="userName",
            field=models.CharField(default="null", editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
