# Generated by Django 4.1.7 on 2023-11-25 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0004_userdata_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="news_providers",
            new_name="news_provider",
        ),
        migrations.AddField(
            model_name="news",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="null",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
