# Generated by Django 4.1.7 on 2023-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0006_alter_news_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="user_id",
            field=models.CharField(max_length=200),
        ),
    ]
