# Generated by Django 4.1.7 on 2023-11-25 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0010_news_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="id",
        ),
    ]
